name: Todo App CI/CD Pipeline

on:
  push:
    branches: [main]

# 途中のpushを自動キャンセル（無駄な並走を防ぐ）
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build • Test • Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Deploy (Firebase Hosting)
        env:
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_BASE64" | base64 -d > $HOME/private-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/private-key.json"
          npm i -g firebase-tools
          firebase deploy --only hosting

      - name: Cleanup
        if: always()
        run: rm -f $HOME/private-key.json
